import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedPrivacyWidget4.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedEllipse2Widget8.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedMoreActionsWidget2.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedProfileBarWidget1.dart';
import 'package:flutterapp/healthkatapp/current_user.dart';
import 'package:flutterapp/helpers/svg/svg.dart';
import 'package:modal_progress_hud/modal_progress_hud.dart';
import 'package:provider/provider.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class Profile extends StatefulWidget {
  @override
  _ProfileState createState() => _ProfileState();
}

class _ProfileState extends State<Profile> {
  Widget build(BuildContext context) {
    bool _loading = false;

    return GestureDetector(
        onTap: () {
          FocusScope.of(context).unfocus();
        },
        child: ModalProgressHUD(
            inAsyncCall: _loading,
            child: Scaffold(
              appBar: AppBar(
                leading: IconButton(
                  icon: Icon(Icons.arrow_back, color: Colors.black),
                  onPressed: () => Navigator.of(context)
                      .pushNamedAndRemoveUntil(
                          '/Intro', (Route<dynamic> route) => false),
                ),
                backgroundColor: Colors.transparent,
                elevation: 0,
              ),
              backgroundColor: Colors.white,
              body: Container(
                child: ListView(
                    shrinkWrap: true,
                    padding: const EdgeInsets.all(10.0),
                    children: <Widget>[
                      Container(
                        child: CircleAvatar(
                          backgroundColor: Colors.white,
                          radius: 70,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(50),
                            child: Icon(
                              Icons.supervised_user_circle,
                              size: 120,
                              color: Colors.green[700],
                            ),
                          ),
                        ),
                      ),
                      Container(
                          child: Center(
                        child: Text(
                          '${Provider.of<CurrentUser>(context, listen: false).displayName}',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 28,
                            fontFamily: 'Nunito',
                          ),
                        ),
                      )),
                      Center(child: Text('Information')),
                      SizedBox(height: 50),
                      Container(
                        child: Row(
                          children: [
                            Container(
                              child: Text('Phone Number : '),
                            ),
                            Container(
                              child: Text(
                                  '${Provider.of<CurrentUser>(context, listen: false).phoneNumber}'),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(height: 20),
                      Container(
                        child: Row(
                          children: [
                            Container(
                              child: Text('Address : '),
                            ),
                            Container(
                              child: Text(
                                  '${Provider.of<CurrentUser>(context, listen: false).address}'),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(height: 20),
                      Container(
                        child: Row(
                          children: [
                            Container(
                              child: Text('Role : '),
                            ),
                            Container(
                              child: Text(Provider.of<CurrentUser>(context,
                                              listen: false)
                                          .isDoctor ==
                                      true
                                  ? 'Doctor'
                                  : 'Patient'),
                            ),
                            Provider.of<CurrentUser>(context, listen: false)
                                        .isDoctor ==
                                    true
                                ? Container(
                                    child: Row(
                                      children: [
                                        Container(
                                          child: Text('Address : '),
                                        ),
                                        Container(
                                          child: Text(
                                              '${Provider.of<CurrentUser>(context, listen: false).address}'),
                                        ),
                                      ],
                                    ),
                                  )
                                : Container()
                          ],
                        ),
                      ),
                      SizedBox(height: 200),
                      Text("More Actions",
                          style: TextStyle(color: Colors.grey)),
                      Divider(),
                      Text("Privacy", style: TextStyle(color: Colors.grey)),
                      Divider()
                    ]),
              ),
            )));
  }
}
