import 'package:flutter/material.dart';

/* Rectangle Rectangle 1
    Autogenerated by FlutLab FTF Generator
  */
class EmailTextField extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return
      Column(
      children: [
        TextField(
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              hintText: 'Enter email address',
            ),
          )
        ]
    )
    ;
  }
}
